# Docker-Compose Version
version: '3.9'
name: 'ticket-platform'
services:
    ticket:
        build:
            context: ./
            dockerfile: docker/ticket/local.Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        tty: true
        volumes:
            - ./:/var/www
        ports:
            - "8083:8083"
        depends_on:
            - mysql
            - redis
        networks:
            - ticket
    # Redis
    redis:
        image: redis:alpine
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        ports:
            - "6380:6379"
        volumes:
            - ticket-redis-data:/data
        networks:
            - ticket
    # MySQL
    mysql:
        image: mysql:latest
        container_name: ticket-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ticket
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        tty: true
        ports:
            - "33061:3306"
        volumes:
            - ticket-mysql-data:/var/lib/mysql
        networks:
            - ticket

volumes:
    ticket-mysql-data:
    ticket-redis-data:
# Networks
networks:
    ticket:
        driver: bridge
