services:
    app:
        build:
            context: .
            dockerfile: docker/ticket/Dockerfile
        container_name: ticket_app
        ports:
            - "8083:8083"
        volumes:
            - .:/app
        environment:
            COMPOSER_ALLOW_SUPERUSER: '1'
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8083"]
        depends_on:
            - db
        networks:
            - ticket-network

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'ticket'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3309:3306'
        volumes:
            - my-db:/var/lib/mysql
        networks:
            - ticket-network

volumes:
    my-db:

networks:
    ticket-network:

